export const GAME_CONFIG = {
    PLAYER: {
      SPEED: 80,
      INITIAL_HP: 100,
      DAMAGE: 20,
      ATTACK_RANGE: 100,
      HP_INCREASE_PER_LEVEL: 20,
      DAMAGE_INCREASE_PER_LEVEL: 5,
      INITIAL_DAMAGE: 20,
    },
    MONSTER: {
      INITIAL_HP: 200,
      DAMAGE_PER_ATTACK: 10,
      ATTACK_RANGE: 40,
      ATTACK_COOLDOWN: 1000,
      CHASE_RANGE: 150,
      IDLE_SPEED: 50,
      CHASE_SPEED: 120,
      SPAWN_INTERVAL: 60000,
      MOVEMENT_UPDATE_TIME: 2000,
    },
    NPC: {
      MOVEMENT_SPEED: 80,
      MOVEMENT_UPDATE_TIME: 3000,
    },
    ITEM_SPAWNER: {
      SPAWN_INTERVAL: 5000,
      MOVEMENT_UPDATE_TIME: 3000,
    },
    INTERACTION_RANGE: 100,
};